# Data representation overview

In this lecture, "data representation" is being used as an alternative to a more common term: "data structures." Where as data structures may refer to any data structure, including avl-trees, b-trees, binary-trees, in other words, low level structures defined with low level programming constructs, this lecture is only concerned with high level data structures used to represent real-world data.

Specifically, we are concernd with data represented as vectors, matrices, dataframes, sql tables - "structured" data. In modern computer science, unstructured data, such as audio, video, text is becoming very common and is now a solved problem. For the purpose of this lecture, we are more interested in the more common data format, sometimes called "tabular" data.

## 1 dimensional vectors

One dimensional data is a foundational data structure, although pehraps too low level for our use. Some examples are common lists, tuples numpy vectors and Pandas series.

In [15]:
import numpy as np
import pandas as pd

In [16]:
ages_list     = [34, 32, 10, 8, 2]
common_tupple = (1,2,3,4,5)

ages_array = np.array([34, 32, 10, 8, 2])
ages_s     = pd.Series([34, 32, 10, 8, 2])

More realistically, we load 2-dimensional data and extract 1 dimensional slices:

In [22]:
ohlc_df = pd.read_csv('../../datasets/market_data/ohlcv_2025-sept.csv.zip')
ohlc_df

,ticker,date,open,high,low,close,volume
0,A,2025-09-02,124.879997,125.519997,121.800003,125.209999,2412700
1,A,2025-09-03,124.959999,125.830002,123.720001,125.220001,2497300
2,A,2025-09-04,125.000000,128.830002,123.800003,128.479996,2715400
3,A,2025-09-05,128.720001,131.000000,128.389999,128.750000,1633200
4,A,2025-09-08,127.480003,128.419998,126.279999,128.130005,2136200
...,...,...,...,...,...,...,...
87556,ZYME,2025-09-24,16.440001,16.610001,16.055000,16.299999,521200
87557,ZYME,2025-09-25,16.180000,16.200001,15.810000,16.160000,563200
87558,ZYME,2025-09-26,16.270000,16.660000,16.059999,16.600000,521700
87559,ZYME,2025-09-29,16.860001,17.600000,16.740000,17.230000,555500


Extract MSFT's closing prices for the month of September (Pandas Series):

In [38]:
msft_sept_s = ohlc_df.loc[ohlc_df.ticker == 'MSFT', 'close'].reset_index(drop=True) # We will look at indexes in a future lecture
msft_sept_s

0     505.119995
1     505.350006
2     507.970001
3     495.000000
4     498.200012
5     498.410004
6     500.369995
7     501.010010
8     509.899994
9     515.359985
10    509.040009
11    510.019989
12    508.450012
13    517.929993
14    514.450012
15    509.230011
16    510.149994
17    507.029999
18    511.459991
19    514.599976
20    517.950012
Name: close, dtype: float64

Extract numpy vector from the Pandas series:

In [39]:
msft_sept_v = msft_sept_s.values
msft_sept_v

array([505.11999512, 505.3500061 , 507.97000122, 495.        ,
       498.20001221, 498.41000366, 500.36999512, 501.01000977,
       509.8999939 , 515.35998535, 509.04000854, 510.01998901,
       508.45001221, 517.92999268, 514.45001221, 509.23001099,
       510.1499939 , 507.02999878, 511.45999146, 514.59997559,
       517.95001221])

Just for good measure, let's extract a normal Python list:

In [40]:
msft_sept_l = msft_sept_s.tolist()
msft_sept_l

[505.1199951171875,
 505.3500061035156,
 507.9700012207031,
 495.0,
 498.2000122070313,
 498.4100036621094,
 500.3699951171875,
 501.010009765625,
 509.8999938964844,
 515.3599853515625,
 509.0400085449219,
 510.0199890136719,
 508.4500122070313,
 517.9299926757812,
 514.4500122070312,
 509.2300109863281,
 510.1499938964844,
 507.0299987792969,
 511.4599914550781,
 514.5999755859375,
 517.9500122070312]

### What can we do with 1-dimensional data?

#### Find prices at a specific index:

In [41]:
msft_sept_l[0] # Get the first value

505.1199951171875

In [42]:
msft_sept_v[0]

np.float64(505.1199951171875)

In [43]:
msft_sept_s[0]

np.float64(505.1199951171875)

#### Get a range of values:

In [45]:
# Get the first 3 values
msft_sept_l[0:3]

[505.1199951171875, 505.3500061035156, 507.9700012207031]

In [46]:
msft_sept_v[0:3]

array([505.11999512, 505.3500061 , 507.97000122])

In [47]:
msft_sept_s[0:3]

0    505.119995
1    505.350006
2    507.970001
Name: close, dtype: float64

#### Aggregate over the values

In [49]:
# Find the average closing price

import statistics

statistics.mean(msft_sept_l)

507.95238095238096

In [50]:
msft_sept_v.mean()

np.float64(507.95238095238096)

In [51]:
msft_sept_s.mean()

np.float64(507.95238095238096)

#### So why do we have three different ways of doing the same thing?

The most obvious answer is speed!

In [54]:
%timeit statistics.mean(msft_sept_l) # list
%timeit msft_sept_v.mean()           # numpy
%timeit msft_sept_s.mean()           # pandas

10.8 μs ± 57.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.32 μs ± 7.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
5.47 μs ± 38 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Btw, you may have thought that numpy and pandas should be about the same speed. However, becaues pandas allows missing values, it is often slower than raw numpy.

But! Speed is not the only difference. Other than handlign missing values, pandas provides additonal functionality for hadling time series data (to be discussed later) and for providing a better developer experience.

For example, a pandas series can be given a name:

In [55]:
msft_sept_s.name = 'MSFT September Closing Price'
msft_sept_s

0     505.119995
1     505.350006
2     507.970001
3     495.000000
4     498.200012
5     498.410004
6     500.369995
7     501.010010
8     509.899994
9     515.359985
10    509.040009
11    510.019989
12    508.450012
13    517.929993
14    514.450012
15    509.230011
16    510.149994
17    507.029999
18    511.459991
19    514.599976
20    517.950012
Name: MSFT September Closing Price, dtype: float64

And we can attach an index which gives more information than just the index location:

In [68]:
ohlc_df2 = ohlc_df.copy() # Create a copy to keep the original unchanges
ohlc_df2 = ohlc_df2.set_index('date') # Set the date column as the index (so each column will be associated with this index)
msft_sept_s2 = ohlc_df2.loc[ohlc_df2.ticker == 'MSFT', 'close'] # Same as before, just extract MSFT's close prices

msft_sept_s2

date
2025-09-02    505.119995
2025-09-03    505.350006
2025-09-04    507.970001
2025-09-05    495.000000
2025-09-08    498.200012
2025-09-09    498.410004
2025-09-10    500.369995
2025-09-11    501.010010
2025-09-12    509.899994
2025-09-15    515.359985
2025-09-16    509.040009
2025-09-17    510.019989
2025-09-18    508.450012
2025-09-19    517.929993
2025-09-22    514.450012
2025-09-23    509.230011
2025-09-24    510.149994
2025-09-25    507.029999
2025-09-26    511.459991
2025-09-29    514.599976
2025-09-30    517.950012
Name: close, dtype: float64

Notice that you now have access to date based ranges, not just index locations!

In [69]:
msft_sept_s2['2025-09-01':'2025-09-10'] # Get the first 10 days of September


date
2025-09-02    505.119995
2025-09-03    505.350006
2025-09-04    507.970001
2025-09-05    495.000000
2025-09-08    498.200012
2025-09-09    498.410004
2025-09-10    500.369995
Name: close, dtype: float64

## 2-dimensional matrices, dataframees and sql tables (and spreadsheets?)

Two dimensional data is several extremely powerful data structures - several of them!

### Matrices
The most obvious is to extend the mathematical vector to a matrix. We have have a name for it, a "matrix!" For our purpose, a matrix is a two dimensional array of numbers. Unlike Python's built-in lists, there is no built-in data structure for tabular data. 

Let's extract a matrix from our prices, say open and closing prices for MSFT for all of September:

In [74]:
msft_oc_m = ohlc_df.loc[ohlc_df.ticker == 'MSFT', ['open', 'close']].values
msft_oc_m

array([[500.47000122, 505.11999512],
       [503.79000854, 505.3500061 ],
       [504.29998779, 507.97000122],
       [509.07000732, 495.        ],
       [498.10998535, 498.20001221],
       [501.42999268, 498.41000366],
       [502.98001099, 500.36999512],
       [502.25      , 501.01000977],
       [506.6499939 , 509.8999939 ],
       [508.79000854, 515.35998535],
       [516.88000488, 509.04000854],
       [510.61999512, 510.01998901],
       [511.48999023, 508.45001221],
       [510.55999756, 517.92999268],
       [515.59002686, 514.45001221],
       [513.79998779, 509.23001099],
       [510.38000488, 510.1499939 ],
       [508.29998779, 507.02999878],
       [510.05999756, 511.45999146],
       [511.5       , 514.59997559],
       [513.23999023, 517.95001221]])

Like before, we can extract values from it. Let's get the opening price for the first day of September:

In [76]:
msft_oc_m[0, 0] # Get the first row, first column (open price for the first day)

np.float64(500.4700012207031)

Get the closing price for the last 3 days of September:

In [77]:
msft_oc_m[-3:, 1] # Get the last 3 rows, second column (close price for the last 3 days)

array([511.45999146, 514.59997559, 517.95001221])

#### Something more interesting average price and average price per category
Have aggregation broken by a category gives us the opportunity to see trends and to compare values for actionable insight.

In [78]:
msft_oc_m.mean()

np.float64(508.0299995059059)

Not very useful. What we if we want average open prices and average closing prices?

In [79]:
msft_oc_m.mean(axis=0) # Get the mean across rows (for each column)

array([508.10761806, 507.95238095])

In [80]:
msft_oc_m.mean(axis=1) # Get the mean across columns (for each row)

array([502.79499817, 504.57000732, 506.13499451, 502.03500366,
       498.15499878, 499.91999817, 501.67500305, 501.63000488,
       508.2749939 , 512.07499695, 512.96000671, 510.31999207,
       509.97000122, 514.24499512, 515.02001953, 511.51499939,
       510.26499939, 507.66499329, 510.75999451, 513.04998779,
       515.59500122])

### Dataframes add a layer of usability on top of matrices

Notice nice column names:

In [84]:
msft_oc_df = pd.DataFrame(msft_oc_m, columns=['open', 'close'])
msft_oc_df.head()

,open,close
0,500.470001,505.119995
1,503.790009,505.350006
2,504.299988,507.970001
3,509.070007,495.000000
4,498.109985,498.200012


same as 

In [85]:
ohlc_df.loc[ohlc_df.ticker == 'MSFT', ['open', 'close']].head()

,open,close
51471,500.470001,505.119995
51472,503.790009,505.350006
51473,504.299988,507.970001
51474,509.070007,495.000000
51475,498.109985,498.200012


Let's add the date index back in:

In [88]:
# Notice that we can't just set the index to 'date', that will bring in dates even where the ticker is not MSFT
msft_oc_df = ohlc_df.loc[ohlc_df.ticker == 'MSFT', ['open', 'close']].set_index(ohlc_df.loc[ohlc_df.ticker == 'MSFT', 'date'])
msft_oc_df.head()

,open,close
date,,
2025-09-02,500.470001,505.119995
2025-09-03,503.790009,505.350006
2025-09-04,504.299988,507.970001
2025-09-05,509.070007,495.000000
2025-09-08,498.109985,498.200012


#### Notice the aggregate function now (it is more oppinionated and easier to use):

In [89]:
msft_oc_df.mean()

open     508.107618
close    507.952381
dtype: float64

We didn't have to tell it to aggregate per open and close column! It understood automatically that it makes no sense to find a mean of all numbers - it has a "business sense!"

In [92]:
msft_oc_df.mean(axis='columns') # Get the mean across columns (for each row)

date
2025-09-02    502.794998
2025-09-03    504.570007
2025-09-04    506.134995
2025-09-05    502.035004
2025-09-08    498.154999
2025-09-09    499.919998
2025-09-10    501.675003
2025-09-11    501.630005
2025-09-12    508.274994
2025-09-15    512.074997
2025-09-16    512.960007
2025-09-17    510.319992
2025-09-18    509.970001
2025-09-19    514.244995
2025-09-22    515.020020
2025-09-23    511.514999
2025-09-24    510.264999
2025-09-25    507.664993
2025-09-26    510.759995
2025-09-29    513.049988
2025-09-30    515.595001
dtype: float64

#### The aggregate function is even more powerful in dataframes - because of the `groupby` clause

In [108]:
msft_oc_df['day_name'] = pd.to_datetime(msft_oc_df.index).day_name()
msft_oc_df.head()

,open,close,day_name
date,,,
2025-09-02,500.470001,505.119995,Tuesday
2025-09-03,503.790009,505.350006,Wednesday
2025-09-04,504.299988,507.970001,Thursday
2025-09-05,509.070007,495.000000,Friday
2025-09-08,498.109985,498.200012,Monday


In [110]:
# Find the average open and close price for each day of the week:
msft_oc_df.groupby('day_name').mean()

,open,close
day_name,,
Friday,509.084999,508.572495
Monday,508.497505,510.652496
Thursday,506.584991,506.115005
Tuesday,509.163995,507.950006
Wednesday,506.942505,506.472496


#### Dataframes provide other useful primitives - let's combine this dataset with another!

In [114]:
sectors_df = pd.read_csv('../../datasets/market_data/sectors.csv.zip', usecols=['ticker', 'industry'])
sectors_df

,ticker,industry
0,A,Medical Diagnostics & Research
1,AA,Metals & Mining
2,AABA,Asset Management
3,AAC,Health Care Providers
4,AADR,NaN
...,...,...
6363,ZTS,Drug Manufacturers
6364,ZUMZ,Retail - Apparel & Specialty
6365,ZUO,Application Software
6366,ZYME,Biotechnology


In [117]:
ohlc_df.head()

,ticker,date,open,high,low,close,volume
0,A,2025-09-02,124.879997,125.519997,121.800003,125.209999,2412700
1,A,2025-09-03,124.959999,125.830002,123.720001,125.220001,2497300
2,A,2025-09-04,125.000000,128.830002,123.800003,128.479996,2715400
3,A,2025-09-05,128.720001,131.000000,128.389999,128.750000,1633200
4,A,2025-09-08,127.480003,128.419998,126.279999,128.130005,2136200


In [119]:
ohlc_sectors_df = ohlc_df.merge(sectors_df, on='ticker', how='left') # Merge the two dataframes on the ticker column (left join)
ohlc_sectors_df.head()

,ticker,date,open,high,low,close,volume,industry
0,A,2025-09-02,124.879997,125.519997,121.800003,125.209999,2412700,Medical Diagnostics & Research
1,A,2025-09-03,124.959999,125.830002,123.720001,125.220001,2497300,Medical Diagnostics & Research
2,A,2025-09-04,125.000000,128.830002,123.800003,128.479996,2715400,Medical Diagnostics & Research
3,A,2025-09-05,128.720001,131.000000,128.389999,128.750000,1633200,Medical Diagnostics & Research
4,A,2025-09-08,127.480003,128.419998,126.279999,128.130005,2136200,Medical Diagnostics & Research


In [121]:
ohlc_sectors_df.loc[ohlc_sectors_df.ticker == 'MSFT'].head()

,ticker,date,open,high,low,close,volume,industry
51471,MSFT,2025-09-02,500.470001,506.000000,496.809998,505.119995,18128000,Application Software
51472,MSFT,2025-09-03,503.790009,507.790009,502.320007,505.350006,16345100,Application Software
51473,MSFT,2025-09-04,504.299988,508.149994,503.149994,507.970001,15509500,Application Software
51474,MSFT,2025-09-05,509.070007,511.970001,492.369995,495.000000,31994800,Application Software
51475,MSFT,2025-09-08,498.109985,501.200012,495.029999,498.200012,16771000,Application Software


In [122]:
ohlc_sectors_df.loc[ohlc_sectors_df.ticker == 'F'].head()

,ticker,date,open,high,low,close,volume,industry
27006,F,2025-09-02,11.76,11.89,11.64,11.72,57704200,Autos
27007,F,2025-09-03,11.67,11.73,11.57,11.62,47728700,Autos
27008,F,2025-09-04,11.65,11.70,11.57,11.68,33136700,Autos
27009,F,2025-09-05,11.71,11.91,11.66,11.74,47547800,Autos
27010,F,2025-09-08,11.75,11.75,11.58,11.69,39734500,Autos


In [123]:
ohlc_sectors_df.loc[ohlc_sectors_df.ticker == 'YUM'].head()

,ticker,date,open,high,low,close,volume,industry
87120,YUM,2025-09-02,145.270004,146.179993,144.309998,145.440002,1619000,Restaurants
87121,YUM,2025-09-03,144.720001,145.020004,143.899994,144.550003,1539100,Restaurants
87122,YUM,2025-09-04,144.660004,145.360001,142.350006,143.669998,1484400,Restaurants
87123,YUM,2025-09-05,143.740005,146.110001,143.740005,144.580002,1455800,Restaurants
87124,YUM,2025-09-08,144.000000,148.039993,143.229996,147.990005,2187700,Restaurants


#### Why don't we find the average closing price per sector?
(although, not the most sensible analysis, it is just to show the power of dataframes)

In [124]:
ohlc_sectors_df.groupby('industry')['close'].mean()

industry
Advertising & Marketing Services            16.722029
Aerospace & Defense                        191.147537
Agriculture                                 37.456645
Airlines                                    55.990992
Application Software                       138.943480
                                              ...    
Travel & Leisure                            69.722453
Truck Manufacturing                         70.368453
Utilities - Independent Power Producers     65.676878
Utilities - Regulated                       55.153247
Waste Management                            84.955496
Name: close, Length: 69, dtype: float64

#### Dataframe make it easy to move columns into rows and rows into columns (for example, for cross-tab analysis):

In [143]:
ohlc_faang_df = ohlc_df[ohlc_df.ticker.isin(['META', 'AAPL', 'AMZN', 'NFLX', 'GOOG'])]
ohlc_faang_df

,ticker,date,open,high,low,close,volume
168,AAPL,2025-09-02,229.250000,230.850006,226.970001,229.720001,44075600
169,AAPL,2025-09-03,237.210007,238.850006,234.360001,238.470001,66427800
170,AAPL,2025-09-04,238.449997,239.899994,236.740005,239.779999,47549400
171,AAPL,2025-09-05,240.000000,241.320007,238.490005,239.690002,54870400
172,AAPL,2025-09-08,239.300003,240.149994,236.339996,237.880005,48999500
...,...,...,...,...,...,...,...
53671,NFLX,2025-09-24,121.861000,122.150002,119.419998,120.394997,27731000
53672,NFLX,2025-09-25,120.308998,121.683998,119.151001,120.823997,19978000
53673,NFLX,2025-09-26,120.542000,121.400002,120.000000,121.060997,19450000
53674,NFLX,2025-09-29,120.500000,122.448997,118.753998,120.640999,30332000


Show close prices per day, per ticker, in an easy to read manner

In [145]:
ohlc_faang_df.pivot(index='date', columns='ticker', values='close')


ticker,AAPL,AMZN,GOOG,NFLX
date,,,,
2025-09-02,229.720001,225.339996,211.990005,121.411003
2025-09-03,238.470001,225.990005,231.100006,122.617996
2025-09-04,239.779999,235.679993,232.660004,125.748001
2025-09-05,239.690002,232.330002,235.169998,124.382004
2025-09-08,237.880005,235.839996,234.160004,124.475998
2025-09-09,234.350006,238.240005,239.940002,126.324997
2025-09-10,226.789993,230.330002,239.559998,124.771004
2025-09-11,230.029999,229.949997,240.779999,120.349998
2025-09-12,234.070007,228.149994,241.380005,118.844002


#### Dataframes often provide built-in visualization

In [126]:
import holoviews as hv
import hvplot.pandas  # noqa: F401  — registers the .hvplot accessor

In [127]:
msft_oc_df.hvplot.line(y='open', label='Open Price')

:Curve   [date]   (open)

#### Dataframes have other features, handling missing values, time series (to be discussed later), and more!

### SQL tables are older than dataframes and still very common. They are out of scope for this class but we do want to place them in context.

For the purpose of our class, SQL tables and relational algebra are the smae (a very controversial statement in many circles). While dataframes are loaded from raw files, sql tables live within a "database management system." They are a step or two removed from raw files. Raw files are ingested into a DBMS, which organizes data into tables, controls appends, deletion, transformations and all operations on them. Since a DBMS owns all data access, they can add optimizations that dataframes never could. For example, what we see as a two dimensional tabel of data, might actually be stored completely different - perhaps each column is a **file of its own**, perhaps the **data lives on a cluster** of 100 machines, perhaps the data is **calculated on the fly**!

#### SQL is a different language!
Here is what it looks like:

Show me all rows and all columns:
```sql
select *
from ohlc
```

Show me all rows and only the ticker, open and close columns:
```sql
select ticker, open, close
from ohlc
```

Show me all rows and only the ticker, open and close columns, **but only for MSFT**:
```sql
select ticker, open, close
from ohlc
where ticker = MSFT
```

Find the mean closing price for each ticker:
```sql
select ticker, avg(close) as avg_close
from ohlc
group by ticker
```

Join the ohlc table with the sectors table to get the industry for each ticker:
```sql
select ticker, industry
from ohlc
join sectors on ohlc.ticker = sectors.ticker
```

Find the mean closing price for each industry:
```sql
select industry, avg(close) as avg_close
from ohlc
join sectors on ohlc.ticker = sectors.ticker
group by industry
```

Show the first 5 rows of this table: ... sqls is not great for this - for one thing, rows are not supposed to have order (similar to mathematical sets)

Show the 2nd, 4th and 7th columns: ... again, sql is not great for this.

Pivot the table so the close column ... actualy many (perhaps most?) sql systems don't provide a robust implementation of pivoting

#### Did you notice that the groupby and merge features of dataframes look very similar to sql? That's where they come from!

Remember: dataframes are generally single files. You load them in your laptop, hence they are limited by the resources on your computer. There are many alternatives and derivatives which let you improve the speed, run them on a gpu, run them across a cluster, etc. But generally speaking, dataframes are extremely handy and a swiss army knife of analysis but are limited by how much data they can process.

SQL tables, on the other hand, have been designed to handle extremely large amounds of data. Databases are often run by dedicated teams.

General advice: **You shold prefer to do as much data processing via sql as possibe, before switching to dataframes**

## N-dimensional data (tensors)
You may have thought that we left numpy behind. Recall that it was faster, but aren't dataframes better for everything else? Numpy (and related libraries, such as Pytorch, MLX, Jax) are designed to handle n-dimensional data.

Imagine a picture: it has a height and width, but it also has a color channel, remmeber RGB?. A typical picture is actually a 3d matrix! See the numpy lecture for a nice example.

We can demonstrate this with our financial data as well. Let's convert our ohlc dataframe to a 3d matrix where rows represent tickers, columns represend open, highl, low, close prices and the z-axis represends dates:

In [128]:
ohlc_df.head()

,ticker,date,open,high,low,close,volume
0,A,2025-09-02,124.879997,125.519997,121.800003,125.209999,2412700
1,A,2025-09-03,124.959999,125.830002,123.720001,125.220001,2497300
2,A,2025-09-04,125.000000,128.830002,123.800003,128.479996,2715400
3,A,2025-09-05,128.720001,131.000000,128.389999,128.750000,1633200
4,A,2025-09-08,127.480003,128.419998,126.279999,128.130005,2136200


In [133]:
ohlc_df.ticker.nunique() # Get the unique tickers

4171

In [134]:
ohlc_df.date.nunique() # Get the unique dates

21

Let's build our 3d numpy matrix
(note that often you will not have to build such matrices yourself. However, you will need to understand them and how to use them)

In [229]:
matrix_per_date = list()

ROWS    = ['AAPL', 'AMZN', 'NFLX', 'GOOG']
COLUMNS = ['ticker', 'date', 'open', 'close']

for key, group in ohlc_df.loc[ohlc_df.ticker.isin(ROWS), COLUMNS].groupby('date'):
    #print(key)
    # Extract matrix where each row represents AAPL, AMZN, GOOD, NFLX and each column represents OPEN, CLOSE prices
    matrix_of_open_close = group.sort_values(by='ticker')[['open', 'close']].to_numpy()
    matrix_per_date.append(matrix_of_open_close)

In [230]:
threed_mat = np.stack(matrix_per_date, axis=2)#.shape
threed_mat.shape

(4, 2, 21)

As the `.shape` attribute above shows, `threed_mat` is a 3 dimensional matrix. 
- Dimension zero has 4 entries (rows represent the 4 tickers)
- Dimension one has 2 entries (columns represent open and close prices)
- Dimension two has 21 entries (depth represents the 21 trading days of September)


In [231]:
# All tickers, open/close values for the first day of September
threed_mat[:, :, 0]

array([[229.25      , 229.72000122],
       [223.52000427, 225.33999634],
       [208.99000549, 211.99000549],
       [119.69999695, 121.41100311]])

Let's double check the numbers:

In [232]:
ohlc_df.loc[(ohlc_df.date == "2025-09-02") & (ohlc_df.ticker.isin(ROWS)), COLUMNS]

,ticker,date,open,close
168,AAPL,2025-09-02,229.250000,229.720001
3528,AMZN,2025-09-02,223.520004,225.339996
33663,GOOG,2025-09-02,208.990005,211.990005
53655,NFLX,2025-09-02,119.699997,121.411003


Checks out!

This is what the 3d matrix looks like in raw form:

In [233]:
threed_mat

array([[[229.25      , 237.21000671, 238.44999695, 240.        ,
         239.30000305, 237.        , 232.19000244, 226.88000488,
         229.22000122, 237.        , 237.17999268, 238.97000122,
         239.97000122, 241.22999573, 248.30000305, 255.88000488,
         255.22000122, 253.21000671, 254.1000061 , 254.55999756,
         254.86000061],
        [229.72000122, 238.47000122, 239.77999878, 239.69000244,
         237.88000488, 234.3500061 , 226.78999329, 230.02999878,
         234.07000732, 236.69999695, 238.1499939 , 238.99000549,
         237.88000488, 245.5       , 256.07998657, 254.42999268,
         252.30999756, 256.86999512, 255.46000671, 254.42999268,
         254.63000488]],

       [[223.52000427, 225.21000671, 231.19000244, 235.19000244,
         234.94000244, 236.36000061, 237.52000427, 231.49000549,
         230.3500061 , 230.63000488, 232.94000244, 233.77000427,
         232.5       , 232.36999512, 230.55999756, 227.83000183,
         224.1499939 , 220.05999756, 219

Yikes! Better to think in terms of its shape:

In [234]:
threed_mat.shape

(4, 2, 21)

Let's find the average open and close price for all symbols, across all days:

In [240]:
threed_mat.mean(axis=2) 

array([[241.90381077, 242.48619007],
       [229.13190642, 228.08952332],
       [242.24714225, 242.9547635 ],
       [122.09923771, 122.04399944]])

Unless you work with tensors daily, even something as simple as finding the right axis to aggregate over can be confusing. It is important to get in the habit of doing sanity checks. **The first check is, does the `.shape` make sense?** If we want to find the mean open and mean close price for each symbol, the resulting table should still have 4 rows (representing each symbol and 2 columns (representing open and close price):

In [241]:
threed_mat.mean(axis=2).shape

(4, 2)

Looks reasonable!

Let's spot check the numbers:

In [245]:
ohlc_df.loc[(ohlc_df.ticker == 'AAPL'), COLUMNS].agg({'open': 'mean', 'close': 'mean'})

open     241.903811
close    242.486190
dtype: float64

In [246]:
ohlc_df.loc[(ohlc_df.ticker == 'NFLX'), COLUMNS].agg({'open': 'mean', 'close': 'mean'})

open     122.099238
close    122.043999
dtype: float64

The first and last rows do indeed match, we should feel much more confident about our calculation.

#### Note that we just calculated means for the whole month, across many tickers, for two different price categories, _in a single, short, command!_
Compare this to the spot check we did with Pandas. Numpy is much more succint (and faster). For experts, it brings immense power! However, for non-experts, this approach can be a bit too concise. 

## Time dimension enables additonal functionality

#### Even basic Python lists can be thought of as supporting "time" or order based features:

Get the **last three** values:

In [250]:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10][-3:]

[8, 9, 10]

Get the **first three characters** of a string:

In [251]:
"Mr. Homer Simpson"[:3]

'Mr.'

#### Basic numpy vectors have some support for time series data:
Find the cumulative sum of a vector at each point:

In [253]:
np.arange(10).cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

More interestingly, given the matrix of open/close prices across several days for AAPL, we can find the change in price as such:

In [260]:
dummy_prices = np.array([
    # Open           Close
    [241, 242], # Day 1
    [229, 228], # Day 2
    [242, 242 ], # Day 3
    [122, 122]  # Day 4
])

dummy_prices

array([[241, 242],
       [229, 228],
       [242, 242],
       [122, 122]])

In [261]:
# Find changes in prices from one day to the next:
dummy_prices[1:, :] - dummy_prices[:-1, :]


array([[ -12,  -14],
       [  13,   14],
       [-120, -120]])

All of a sudden, you are on your way to making prices for arbitrary number of symbols stationary and ready for further analysis. 

(note that proper stationarization is a bit more involved. For one thing, you are likely to do a diff over logs, but this is a good start)


### Pandas series and dataframes have a rich set of time series features.


Recall from earlier that we set the date column as the index:

In [271]:
ohlc_df2 = ohlc_df.copy() # Create a copy to keep the original unchanges
ohlc_df2.date = pd.to_datetime(ohlc_df2.date) # Convert the date column to datetime format
ohlc_df2 = ohlc_df2.set_index('date') # Set the date column as the index (so each column will be associated with this index)
ohlc_df2 = ohlc_df2.sort_index() # Sort dataset by index (unfortunately, necessary)

In [272]:
ohlc_df2

,ticker,open,high,low,close,volume
date,,,,,,
2025-09-02,A,124.879997,125.519997,121.800003,125.209999,2412700
2025-09-02,ESRT,7.600000,7.620000,7.480000,7.550000,1252100
2025-09-02,ESQ,96.980003,97.750000,95.430000,96.250000,66000
2025-09-02,ESPR,2.220000,2.420000,2.200000,2.320000,7952600
2025-09-02,USAU,13.170000,13.660000,12.930000,13.590000,318600
...,...,...,...,...,...,...
2025-09-30,IWL,165.210007,166.179993,164.990005,166.100006,70600
2025-09-30,CHI,10.740000,10.820000,10.670000,10.790000,215200
2025-09-30,TDTT,24.320000,24.350000,24.320000,24.330000,300400


#### We can use the sample method to resample the data to a different frequency. 
Instead of daily data, say we want it every 3 days, and we instruct Pandas to do so by taking a mean of daily values

In [294]:
apple_close_px_df = ohlc_df2.loc[ohlc_df2.ticker == 'AAPL', ['close']]
apple_close_px_df.head()

,close
date,
2025-09-02,229.720001
2025-09-03,238.470001
2025-09-04,239.779999
2025-09-05,239.690002
2025-09-08,237.880005


In [295]:
apple_close_px_df.resample('3d').mean()

,close
date,
2025-09-02,235.990000
2025-09-05,239.690002
2025-09-08,233.006668
2025-09-11,232.050003
2025-09-14,237.424995
2025-09-17,240.790003
2025-09-20,256.079987
2025-09-23,254.536662
2025-09-26,255.460007


#### We can use the `shift` operator to find the change in price from one day to the next:

In [296]:
# shift(1) brings yesterday's closing price down to today's row
apple_close_px_df - apple_close_px_df.shift(1)

,close
date,
2025-09-02,NaN
2025-09-03,8.750000
2025-09-04,1.309998
2025-09-05,-0.089996
2025-09-08,-1.809998
2025-09-09,-3.529999
2025-09-10,-7.560013
2025-09-11,3.240005
2025-09-12,4.040009


#### Almost just as easily, we can find moving averages with the `rolling` operator:

In [298]:
# Takes the last 20 rows, calculates the mean, and puts it on the current row
apple_close_px_df['close'].rolling(window=3).mean()

date
2025-09-02           NaN
2025-09-03           NaN
2025-09-04    235.990000
2025-09-05    239.313334
2025-09-08    239.116669
2025-09-09    237.306671
2025-09-10    233.006668
2025-09-11    230.389999
2025-09-12    230.296666
2025-09-15    233.600001
2025-09-16    236.306666
2025-09-17    237.946665
2025-09-18    238.340001
2025-09-19    240.790003
2025-09-22    246.486664
2025-09-23    252.003326
2025-09-24    254.273326
2025-09-25    254.536662
2025-09-26    254.880000
2025-09-29    255.586665
2025-09-30    254.840001
Name: close, dtype: float64

In [300]:
# You only need to import this once at the top of your notebook
import hvplot.pandas 

# 1. Calculate the moving average (same as before)
apple_close_px_df['SMA_3'] = apple_close_px_df['close'].rolling(window=3).mean()

# 2. The hvplot magic! 
# By passing a list to 'y', it plots both columns on the same chart automatically.
apple_close_px_df.hvplot.line()

:NdOverlay   [Variable]
   :Curve   [date]   (value)

In [302]:
apple_close_px_df.head()

,close,SMA_3
date,,
2025-09-02,229.720001,NaN
2025-09-03,238.470001,NaN
2025-09-04,239.779999,235.990000
2025-09-05,239.690002,239.313334
2025-09-08,237.880005,239.116669
